mytestkey=This value is from LOCAL properties file
stripe.create-session_.url=https://api.stripe.com/v1/checkout/sessions
stripe.get-session.url=https://api.stripe.com/v1/checkout/sessions/{id}
stripe.expire-session.url=https://api.stripe.com/v1/checkout/sessions/{id}/expire

stripe.password=
stripe.apiKey=sk_test_51QrNIpRcidL4elcRc7D8FDnzPYW02b9mJ09s4BHOQfc2uiX3qp6QDVA6PkRV3HAfwBkwH6CdAicqUmgMEoDAIRDB001bUceAQv

management.tracing.enabled=true
management.tracing.sampling.probability=1.0

