spring.profiles.active=@spring.profiles.active@

server.port=8083

spring.application.name=stripe-provider-service
logging.level.com.hulkhiretech=debug
logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}

